#!make
# Makefile for Freya
# $Id: configure 570 2005-12-01 23:15:33Z Yor $
# This file is automatically generated. There's no point trying to modify it !

# Following values are master values. Any change will have effect on the whole compilation process.
SVN = $(shell cat .svn/entries 2>/dev/null | grep revision | head -n 1 | sed -e 's/^[^"]*"//;s/"[^"]*$$//')
CC = /usr/bin/gcc
AR = /usr/bin/ar
CFLAGS = -pipe -Wall -g -ggdb -I../include -I/usr/include/mysql -DSVN_REVISION=$(SVN).0
LDFLAGS = 
LIBS = -L../lib -L/usr/lib -lcrypt -lnsl -lmysqlclient -ldl -lz -lm

export MAKE CC AR CFLAGS LIBS SVN LDFLAGS

all: title  locales common login char_sql login_txt-converter char_txt-converter ladmin map addons

.PHONY: common login char_sql login_txt-converter char_txt-converter ladmin map addons  locales  locales_clean txt txt-win32 sql title

title:
	@echo -e "\033[37;44m          (=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=)\033[K\033[0m"
	@echo -e "\033[0;44m          (\033[1m         (c)2004-2005 Free Yor team presents :           \033[0;44m)\033[K\033[0m"
	@echo -e "\033[0;44m          (\033[1m         ___   ___    ___   _  _   __                    \033[0;44m)\033[K\033[0m"
	@echo -e "\033[0;44m          (\033[1m        (  _) (  ,)  (  _) ( \/ ) (  )                   \033[0;44m)\033[K\033[0m"
	@echo -e "\033[0;44m          (\033[1m        (  _)  )  \   ) _)  \  /  /__\                   \033[0;44m)\033[K\033[0m"
	@echo -e "\033[0;44m          (\033[1m        (_)   (_)\_) (___) (__/  (_)(_) v2.0.2           \033[0;44m)\033[K\033[0m"
	@echo -e "\033[0;44m          (\033[1m          Free Ragnarok Emulator, Yor Adopted.           \033[0;44m)\033[K\033[0m"
	@echo -e "\033[0;44m          (\033[1m                http://www.ro-freya.net                  \033[0;44m)\033[K\033[0m"
	@echo -e "\033[37;44m          (=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=)\033[K\033[0m"
	@echo
	@echo "Compiling Freya v2.0.2 (SVN#$(SVN)) (MySQL GetText)"
	@echo

common: 
	@echo -e " - DIR\tsrc/common"
	@$(MAKE) --no-print-directory -C src/common/ libcommon.a

login:  common
	@echo -e " - DIR\tsrc/login"
	@$(MAKE) --no-print-directory -C src/login/ ../../login-server

char_sql:  common
	@echo -e " - DIR\tsrc/char_sql"
	@$(MAKE) --no-print-directory -C src/char_sql/ ../../char-server

login_txt-converter:  common
	@echo -e " - DIR\tsrc/login_txt-converter"
	@$(MAKE) --no-print-directory -C src/login_txt-converter/ ../../login-converter

char_txt-converter:  common
	@echo -e " - DIR\tsrc/char_txt-converter"
	@$(MAKE) --no-print-directory -C src/char_txt-converter/ ../../char-converter

ladmin:  common
	@echo -e " - DIR\tsrc/ladmin"
	@$(MAKE) --no-print-directory -C src/ladmin/ ../../ladmin

map:  common
	@echo -e " - DIR\tsrc/map"
	@$(MAKE) --no-print-directory -C src/map/ ../../map-server

addons:  common
	@echo -e " - DIR\tsrc/addons"
	@$(MAKE) --no-print-directory -C src/addons/ lib../../addons.a

clean:  locales_clean
	@$(MAKE) -C src/common/ clean
	@$(MAKE) -C src/login/ clean
	@$(MAKE) -C src/char_sql/ clean
	@$(MAKE) -C src/login_txt-converter/ clean
	@$(MAKE) -C src/char_txt-converter/ clean
	@$(MAKE) -C src/ladmin/ clean
	@$(MAKE) -C src/map/ clean
	@$(MAKE) -C src/addons/ clean

locales:
	@echo -e " - DIR\tlocales"
	@for foo in locales/*/; do \
		echo -e "   LOC\t"`basename $${foo}`; \
		msgfmt -c -o $${foo}/LC_MESSAGES/npcs.mo $${foo}/LC_MESSAGES/npcs.po; \
	done

locales_clean:
	find locales/ -name '*.mo' -exec rm -f {} \;

txt:
	./configure --with-make

txt-win32:
	./configure --with-win32 --with-make

sql:
	./configure --with-mysql --with-make

