#!make
# Makefile for Freya
# $Id: configure 570 2005-12-01 23:15:33Z Yor $
# This file is automatically generated. There's no point trying to modify it !

# Following values are master values. Any change will have effect on the whole compilation process.
SVN = $(shell cat .svn/entries 2>/dev/null | grep revision | head -n 1 | sed -e 's/^[^"]*"//;s/"[^"]*$$//')
CC = /usr/bin/gcc
AR = /usr/bin/ar
CFLAGS = -pipe -Wall -g -ggdb -I../include -DSVN_REVISION=$(SVN).0
LDFLAGS = 
LIBS = -L../lib -lz -lm

export MAKE CC AR CFLAGS LIBS SVN LDFLAGS

all: title  common login char ladmin tool map

.PHONY: common login char ladmin tool map   txt txt-win32 sql title

title:
	@echo -e "\033[37;44m          (=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=)\033[K\033[0m"
	@echo -e "\033[0;44m          (\033[1m           (c)2004-2007 Freya team presents:             \033[0;44m)\033[K\033[0m"
	@echo -e "\033[0;44m          (\033[1m         ___   ___    ___   _  _   __                    \033[0;44m)\033[K\033[0m"
	@echo -e "\033[0;44m          (\033[1m        (  _) (  ,)  (  _) ( \/ ) (  )                   \033[0;44m)\033[K\033[0m"
	@echo -e "\033[0;44m          (\033[1m        (  _)  )  \   ) _)  \  /  /__\                   \033[0;44m)\033[K\033[0m"
	@echo -e "\033[0;44m          (\033[1m        (_)   (_)\_) (___) (__/  (_)(_) v3.1             \033[0;44m)\033[K\033[0m"
	@echo -e "\033[0;44m          (\033[1m              http://www.ro-freya.net/                    \033[0;44m)\033[K\033[0m"
	@echo -e "\033[37;44m          (=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=)\033[K\033[0m"
	@echo
	@echo -n "Compiling Freya v3.1 (SVN#$(SVN))"
	@echo

common: 
	@echo -e " - DIR\tsrc/common"
	@$(MAKE) --no-print-directory -C src/common/ libcommon.a

login:  common
	@echo -e " - DIR\tsrc/login"
	@$(MAKE) --no-print-directory -C src/login/ ../../login-server.exe

char:  common
	@echo -e " - DIR\tsrc/char"
	@$(MAKE) --no-print-directory -C src/char/ ../../char-server.exe

ladmin:  common
	@echo -e " - DIR\tsrc/ladmin"
	@$(MAKE) --no-print-directory -C src/ladmin/ ../../ladmin.exe

tool:  common
	@echo -e " - DIR\tsrc/tool"
	@$(MAKE) --no-print-directory -C src/tool/ 

map:  common
	@echo -e " - DIR\tsrc/map"
	@$(MAKE) --no-print-directory -C src/map/ ../../map-server.exe

clean: 
	@$(MAKE) -C src/common/ clean
	@$(MAKE) -C src/login/ clean
	@$(MAKE) -C src/char/ clean
	@$(MAKE) -C src/ladmin/ clean
	@$(MAKE) -C src/tool/ clean
	@$(MAKE) -C src/map/ clean



txt:
	./configure --with-make

txt-win32:
	./configure --with-win32 --with-make

sql:
	./configure --with-mysql --with-make

sql-win32:
	./configure --with-mysql --with-win32 --with-make

