del login-server.exe
del char-server.exe
del map-server.exe
del txt-converter.exe
del src\common\zlib\*.obj
del src\common\*.obj
del src\char\*.obj
del src\login\*.obj
del src\map\*.obj
del src\converter\*.obj